apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-prodcution-e2e-pipeline-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: complete-prodcution-e2e-pipeline
  template:
    metadata:
      labels:
        app: complete-prodcution-e2e-pipeline
    spec:
      containers:
      - name: complete-prodcution-e2e-pipeline
        image: oumymajellali/complete-prodcution-e2e-pipeline:1.0.0-35
        ports:
        - containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: complete-prodcution-e2e-pipeline-service
spec:
  selector:
    app: complete-prodcution-e2e-pipeline
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30002
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: complete-prodcution-e2e-pipeline
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30003
  type: NodePort
