apiVersion: v1
kind: Service
metadata:
  name: complete-prodcution-e2e-pipeline-service
spec:
  selector:
    app: complete-prodcution-e2e-pipeline
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
  type: NodePort 