apiVersion: v1
kind: Service
metadata:
  name: complete-prodcution-e2e-pipeline-service
spec:
  selector:
    app: complete-prodcution-e2e-pipeline
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30002
  type: NodePort 